### config/credentials.yml

# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: <your-secret-hash>

# used for e.g. ActionMailer email delivery
email:
  user: <email-adress>
  password: <email-pass>

# database access in production environment
production:
  database:
    database: <production-database-name>
    username: <database-user>
    password: <database-pass>
    host: <database-host>

# ActiveStorage file storing in the cloud
aws: 
  access_key_id: <aws-key-id>
  secret_access_key: <aws-secret-key>
